"""initial catalog schema

Revision ID: a82a9db11860
Revises: 
"""
import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision = 'a82a9db11860'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captures',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('rig_type', sa.Enum('HEAD_MOUNTED', 'UMI_GRIPPER', 'STEREO', 'GLOVE', 'TELEOP_ROBOT', 'DEXUMI_EXOSKELETON', name='rig_type'), nullable=False),
    sa.Column('raw_uri', sa.Text(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captures_content_hash'), 'captures', ['content_hash'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.Enum('STAGE1_VOLUME', 'STAGE2_ANCHOR', name='tier'), nullable=True),
    sa.Column('manifest_uri', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer', 'name', 'version', name='uq_dataset_version')
    )
    op.create_index(op.f('ix_datasets_customer'), 'datasets', ['customer'], unique=False)
    op.create_table('demonstrators',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embodiments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('arm_dof', sa.Integer(), nullable=False),
    sa.Column('hand_dof', sa.Integer(), nullable=True),
    sa.Column('urdf_uri', sa.Text(), nullable=True),
    sa.Column('sim_validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rigs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('rig_type', sa.Enum('HEAD_MOUNTED', 'UMI_GRIPPER', 'STEREO', 'GLOVE', 'TELEOP_ROBOT', 'DEXUMI_EXOSKELETON', name='rig_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent',
    sa.Column('capture_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('GRANTED', 'PENDING', 'DENIED', 'REVOKED', name='consent_status'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conflict_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capture_id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('capture_id', sa.String(length=64), nullable=False),
    sa.Column('rig_type', sa.Enum('HEAD_MOUNTED', 'UMI_GRIPPER', 'STEREO', 'GLOVE', 'TELEOP_ROBOT', 'DEXUMI_EXOSKELETON', name='rig_type'), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=True),
    sa.Column('demonstrator_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('canonical_uri', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('STAGE1_VOLUME', 'STAGE2_ANCHOR', name='tier'), nullable=True),
    sa.Column('effective_hours', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['demonstrator_id'], ['demonstrators.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_capture_id'), 'episodes', ['capture_id'], unique=False)
    op.create_index(op.f('ix_episodes_demonstrator_id'), 'episodes', ['demonstrator_id'], unique=False)
    op.create_index(op.f('ix_episodes_scene_id'), 'episodes', ['scene_id'], unique=False)
    op.create_index(op.f('ix_episodes_task_id'), 'episodes', ['task_id'], unique=False)
    op.create_index('ix_episodes_task_tier', 'episodes', ['task_id', 'tier'], unique=False)
    op.create_table('annotations',
    sa.Column('episode_id', sa.String(length=128), nullable=False),
    sa.Column('paraphrases', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('subtasks_uri', sa.Text(), nullable=True),
    sa.Column('subgoal_frames', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id')
    )
    op.create_table('certifications',
    sa.Column('episode_id', sa.String(length=128), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('mistakes', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('strategy_alignment', sa.Text(), nullable=True),
    sa.Column('pii_status', sa.Enum('PASSED', 'PENDING', 'FAILED', name='pii_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quality IS NULL OR (quality >= 1 AND quality <= 5)', name='ck_quality_1_5'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id')
    )
    op.create_table('episode_embeddings',
    sa.Column('episode_id', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id', 'model')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('episode_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('checkpoint_uri', sa.Text(), nullable=True),
    sa.Column('logs_uri', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_stage'), 'jobs', ['stage'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('retarget_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.String(length=128), nullable=False),
    sa.Column('embodiment_id', sa.String(length=64), nullable=False),
    sa.Column('joint_traj_uri', sa.Text(), nullable=True),
    sa.Column('ee_traj_uri', sa.Text(), nullable=True),
    sa.Column('sim_validation_passed', sa.Boolean(), nullable=True),
    sa.Column('sim_validation_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['embodiment_id'], ['embodiments.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'embodiment_id', name='uq_episode_embodiment')
    )
    op.create_index(op.f('ix_retarget_results_embodiment_id'), 'retarget_results', ['embodiment_id'], unique=False)
    op.create_index(op.f('ix_retarget_results_episode_id'), 'retarget_results', ['episode_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retarget_results_episode_id'), table_name='retarget_results')
    op.drop_index(op.f('ix_retarget_results_embodiment_id'), table_name='retarget_results')
    op.drop_table('retarget_results')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_stage'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('episode_embeddings')
    op.drop_table('certifications')
    op.drop_table('annotations')
    op.drop_index('ix_episodes_task_tier', table_name='episodes')
    op.drop_index(op.f('ix_episodes_task_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_scene_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_demonstrator_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_capture_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_table('consent')
    op.drop_table('tasks')
    op.drop_table('scenes')
    op.drop_table('rigs')
    op.drop_table('embodiments')
    op.drop_table('demonstrators')
    op.drop_index(op.f('ix_datasets_customer'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_captures_content_hash'), table_name='captures')
    op.drop_table('captures')
    # ### end Alembic commands ###
