"""content-addressed captures + consent event log

Revision ID: a8ed971f9fde
Revises: a82a9db11860
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'a8ed971f9fde'
down_revision = 'a82a9db11860'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capture_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.Enum('RECORDED', 'DUPLICATE_CONFLICT', 'REVOKED', 'RECONCILED', name='consent_event_type'), nullable=False),
    sa.Column('status', postgresql.ENUM(name='consent_status', create_type=False), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_events_capture_id'), 'consent_events', ['capture_id'], unique=False)
    op.add_column('captures', sa.Column('size_bytes', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('captures', 'size_bytes')
    op.drop_index(op.f('ix_consent_events_capture_id'), table_name='consent_events')
    op.drop_table('consent_events')
    # ### end Alembic commands ###
