"""DataStack — Aurora Serverless v2 Postgres + Secrets Manager.

AWS Architecture §3 (the catalog) and §7 (cost pragmatics: "Aurora Serverless v2
min-capacity ... to idle cheaply on credits"). Serverless v2 scales to 0.5 ACU when idle,
which matters when the corpus is one recording and the database is mostly asleep.

Glue/Athena are in the doc's DataStack but out of the Increment-1 scope list — they are
for heavy diversity analytics over canonical Parquet, which is meaningless until there is
more than one capture. Deferred, deliberately.

**No credentials in code.** The master password is generated by Secrets Manager and never
leaves AWS; the app reads it by ARN (`ACTUATE_DB_SECRET_ARN`).
"""

from __future__ import annotations

import aws_cdk as cdk
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_kms as kms
from aws_cdk import aws_rds as rds
from constructs import Construct


class DataStack(cdk.Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        env_name: str,
        key: kms.IKey,
        with_bastion: bool = False,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)
        is_prod = env_name == "prod"

        # One NAT gateway, not one per AZ. NAT is a top-3 surprise cost on a small
        # account and there is no availability requirement here worth 3x the bill.
        self.vpc = ec2.Vpc(
            self,
            "Vpc",
            vpc_name=f"actuate-{env_name}",
            max_azs=2,
            nat_gateways=1 if is_prod else 0,
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    name="public", subnet_type=ec2.SubnetType.PUBLIC, cidr_mask=24
                ),
                ec2.SubnetConfiguration(
                    name="isolated",
                    subnet_type=ec2.SubnetType.PRIVATE_ISOLATED,
                    cidr_mask=24,
                ),
            ],
        )

        self.security_group = ec2.SecurityGroup(
            self,
            "DbSg",
            vpc=self.vpc,
            # ASCII only -- EC2 rejects a GroupDescription outside its allowed charset,
            # same class of failure as the IAM role description above.
            description="Actuate catalog. No ingress rules here on purpose: compute "
            "stacks add their own, so the DB is never open to the VPC by default.",
            allow_all_outbound=False,
        )

        self.cluster = rds.DatabaseCluster(
            self,
            "Catalog",
            engine=rds.DatabaseClusterEngine.aurora_postgres(
                # pgvector needs PG >= 15 for the version we pin in the app.
                # 16.4 is only offered as Aurora "limitless" in eu-north-1; the latest
                # standard 16.x available there is 16.13. `.of()` avoids depending on the
                # CDK enum carrying this exact patch level.
                version=rds.AuroraPostgresEngineVersion.of("16.13", "16")
            ),
            cluster_identifier=f"actuate-catalog-{env_name}",
            default_database_name="actuate",
            # Master credentials are GENERATED and stored in Secrets Manager. There is no
            # password anywhere in this repo, and there never will be.
            credentials=rds.Credentials.from_generated_secret(
                "actuate_admin", secret_name=f"actuate/{env_name}/catalog"
            ),
            writer=rds.ClusterInstance.serverless_v2("writer"),
            # min_capacity=0 means the cluster AUTO-PAUSES when idle: ~$0/month rather than
            # ~$45/month for a database that, with one capture in it, will be asleep almost
            # all the time. Cost is ~95% of the idle bill for this whole environment, so
            # this is the single line that matters (AWS Architecture §7).
            #
            # Trade-off, stated plainly: the first query after a pause takes ~15s to wake.
            # That is fine for a batch catalog and would not be for a latency-sensitive API.
            # Prod keeps a warm floor.
            serverless_v2_min_capacity=0 if not is_prod else 0.5,
            serverless_v2_max_capacity=8 if is_prod else 2,
            serverless_v2_auto_pause_duration=(
                None if is_prod else cdk.Duration.minutes(10)
            ),
            vpc=self.vpc,
            vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_ISOLATED),
            security_groups=[self.security_group],
            storage_encrypted=True,
            storage_encryption_key=key,
            backup=rds.BackupProps(retention=cdk.Duration.days(14 if is_prod else 1)),
            deletion_protection=is_prod,
            removal_policy=cdk.RemovalPolicy.RETAIN if is_prod else cdk.RemovalPolicy.DESTROY,
        )

        cdk.CfnOutput(self, "DbSecretArn", value=self.cluster.secret.secret_arn)
        cdk.CfnOutput(self, "DbEndpoint", value=self.cluster.cluster_endpoint.hostname)
        cdk.CfnOutput(self, "VpcId", value=self.vpc.vpc_id)

        # The bastion lives INSIDE this stack, not beside it. It needs the VPC and it adds
        # the one ingress rule to the DB security group -- as a separate stack that is a
        # dependency cycle (Data -> Bastion for the SG, Bastion -> Data for the VPC), which
        # CDK rejects outright. Same stack, no cycle.
        self.bastion = None
        if with_bastion:
            from stacks.bastion import SsmBastion

            self.bastion = SsmBastion(
                self,
                "Bastion",
                env_name=env_name,
                vpc=self.vpc,
                db_security_group=self.security_group,
            )
            cdk.CfnOutput(
                self, "BastionInstanceId", value=self.bastion.instance.instance_id
            )
